import { X } from 'lucide-react';

interface TermsAndConditionsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsAndConditionsModal({ isOpen, onClose }: TermsAndConditionsModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[120] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60" onClick={onClose} />
      <div className="relative bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden animate-scale-in">
        {/* Header */}
        <div className="relative gradient-gold px-6 py-5 rounded-t-2xl flex-shrink-0">
          <button onClick={onClose} className="absolute top-4 right-4 text-white/80 hover:text-white transition-colors">
            <X size={20} />
          </button>
          <h2 className="text-2xl font-bold text-white pr-8">Terms and Conditions</h2>
        </div>

        {/* Content - Scrollable */}
        <div className="flex-1 overflow-y-auto px-6 py-6">
          <div className="space-y-4 text-sm text-[#555] leading-relaxed">
            <p>
              This form is an application and its acceptance constitutes an agreement on the part of Deal Forever and the applicant to appoint an individual as a self-employed and independent Distributor. For consumers joining online, the documents constituting the Distributorship Contract apply. For consumers joining online to buy products, the Terms and Conditions of the Distributor Contract apply, and for any purchases of goods or services, the Deal Forever Refund Policy applies. This form read with My Success Plan (as amended from time to time) and all policies/circulars etc. issued by Deal Forever from time to time shall together govern the relationship between the Distributor and Deal Forever and both parties shall be bound by such terms and conditions.
            </p>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Eligibility and Responsibilities:</h3>
              <p>
                Each applicant should be at least 18 years of age at the time of application, to become a Deal Forever Distributor. In case of residence in Maharashtra, I confirm that I am 21 years old and/or above. The Contract between the Distributor and Deal Forever is on a principal-to-principal basis. The signing of this Form / Application by a Distributor & its acceptance does not bind the Distributor as an employee or agent of the Company.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Product and Service Guidelines:</h3>
              <p>
                Distributors are not permitted, under any circumstances to advertise, market or deal in any manner with any product and/or services, which are not approved by Deal Forever in its network. The Distributor shall not make any claim that is not consistent with claims authorised by Deal Forever. The Distributor shall attend the mandatory orientation (face to face / online session) given by Deal Forever regarding provision of fair and accurate information on all aspects of the direct selling operation, remuneration system and expected remuneration for newly recruited Distributors. The date of such an orientation session will be available to the Distributor on company's website.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Confidentiality and E-commerce:</h3>
              <p>
                The Distributor shall take appropriate steps to ensure protection of all confidential information provided to him/her by customers as well as confidential information generated by him during the course of his Distributorship. The Distributor is permitted to sell the products/services on an e-commerce platform/marketplace, only if he/she has taken prior written consent from Deal Forever to do the same. The distributorship is non-transferable.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Complaints and Payments:</h3>
              <p>
                As provided in My Success Plan (as amended from time to time), in case of any grievance or complaint received by the Distributor from a Consumer regarding any product of Deal Forever sold in pursuance of this contract, the Distributor shall refer such complaint to the Grievances Redressal Committee of Deal Forever which shall address such grievances within 30 (Thirty) days. The Decision of the Grievance Redressal Committee regarding such complaints shall be final.
              </p>
              <p className="mt-2">
                The Distributors shall mandatorily provide his/her bank account details to Deal Forever. If the Distributor's bank account details are not updated with Deal Forever and if the Distributor is entitled to a monthly commission between Rs. 100 to 499 then Deal Forever may issue a product voucher against such accrued commission amount. (Payout will be made only when cumulative bonus reaches Rs. 100).
              </p>
              <p className="mt-2">
                The Distributor hereby authorises Deal Forever to send Text Messages related to Deal Forever Business updates on his/her registered mobile number with Deal Forever and authorises Deal Forever to retain all information concerning him and his distributorship.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Jurisdiction and Disputes:</h3>
              <p>
                All disputes are subject to the jurisdiction of New Delhi, India.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-[#191717] mb-2">Nominee and Cooling-Off Period:</h3>
              <p>
                The Distributor's spouse shall be deemed to be his/her nominee unless the Distributor has nominated someone else as the nominee in the DAF or subsequently has submitted the prescribed nomination form and has nominated some other person/entity as his/her nominee. In case the Distributor submits a nomination form either at the time of the submission of the DAF or subsequently, the nomination made in the nomination form shall take precedence over the nomination made in the DAF, in case of a conflict.
              </p>
              <p className="mt-2">
                There shall be a cooling-off period of 30 days along with a buyback policy which are mentioned in details in the business plan (My Success Plan).
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-100 flex-shrink-0">
          <button onClick={onClose} className="btn-primary w-full rounded-lg">
            I Understand & Accept
          </button>
        </div>
      </div>
    </div>
  );
}